import { TestBed } from '@angular/core/testing';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import dayjs from 'dayjs/esm';

import { DATE_TIME_FORMAT } from 'app/config/input.constants';
import { IBlocos, Blocos } from '../blocos.model';

import { BlocosService } from './blocos.service';

describe('Blocos Service', () => {
  let service: BlocosService;
  let httpMock: HttpTestingController;
  let elemDefault: IBlocos;
  let expectedResult: IBlocos | IBlocos[] | boolean | null;
  let currentDate: dayjs.Dayjs;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
    });
    expectedResult = null;
    service = TestBed.inject(BlocosService);
    httpMock = TestBed.inject(HttpTestingController);
    currentDate = dayjs();

    elemDefault = {
      id: 0,
      zeroAM: currentDate,
      zeroAMeDez: currentDate,
      zeroAMeVinte: currentDate,
      zeroAMeTrinta: currentDate,
      zeroAMeQuarenta: currentDate,
      zeroAMeCinquenta: currentDate,
      zeroPM: currentDate,
      zeroPMeDez: currentDate,
      zeroPMeVinte: currentDate,
      zeroPMeTrinta: currentDate,
      zeroPMeQuarenta: currentDate,
      zeroPMeCinquenta: currentDate,
      umAM: currentDate,
      umAMeDez: currentDate,
      umAMeVinte: currentDate,
      umAMeTrinta: currentDate,
      umAMeQuarenta: currentDate,
      umAMeCinquenta: currentDate,
      umPM: currentDate,
      umPMeDez: currentDate,
      umPMeVinte: currentDate,
      umPMeTrinta: currentDate,
      umPMeQuarenta: currentDate,
      umPMeCinquenta: currentDate,
      doisAM: currentDate,
      doisAMeDez: currentDate,
      doisAMeVinte: currentDate,
      doisAMeTrinta: currentDate,
      doisAMeQuarenta: currentDate,
      doisAMeCinquenta: currentDate,
      doisPM: currentDate,
      doisPMeDez: currentDate,
      doisPMeVinte: currentDate,
      doisPMeTrinta: currentDate,
      doisPMeQuarenta: currentDate,
      doisPMeCinquenta: currentDate,
      tresAM: currentDate,
      tresAMeDez: currentDate,
      tresAMeVinte: currentDate,
      tresAMeTrinta: currentDate,
      tresAMeQuarenta: currentDate,
      tresAMeCinquenta: currentDate,
      tresPM: currentDate,
      tresPMeDez: currentDate,
      tresPMeVinte: currentDate,
      tresPMeTrinta: currentDate,
      tresPMeQuarenta: currentDate,
      tresPMeCinquenta: currentDate,
      quatroAM: currentDate,
      quatroAMeDez: currentDate,
      quatroAMeVinte: currentDate,
      quatroAMeTrinta: currentDate,
      quatroAMeQuarenta: currentDate,
      quatroAMeCinquenta: currentDate,
      quatroPM: currentDate,
      quatroPMeDez: currentDate,
      quatroPMeVinte: currentDate,
      quatroPMeTrinta: currentDate,
      quatroPMeQuarenta: currentDate,
      quatroPMeCinquenta: currentDate,
      cincoAM: currentDate,
      cincoAMeDez: currentDate,
      cincoAMeVinte: currentDate,
      cincoAMeTrinta: currentDate,
      cincoAMeQuarenta: currentDate,
      cincoAMeCinquenta: currentDate,
      cincoPM: currentDate,
      cincoPMeDez: currentDate,
      cincoPMeVinte: currentDate,
      cincoPMeTrinta: currentDate,
      cincoPMeQuarenta: currentDate,
      cincoPMeCinquenta: currentDate,
      seisAM: currentDate,
      seisAMeDez: currentDate,
      seisAMeVinte: currentDate,
      seisAMeTrinta: currentDate,
      seisAMeQuarenta: currentDate,
      seisAMeCinquenta: currentDate,
      seisPM: currentDate,
      seisPMeDez: currentDate,
      seisPMeVinte: currentDate,
      seisPMeTrinta: currentDate,
      seisPMeQuarenta: currentDate,
      seisPMeCinquenta: currentDate,
      seteAM: currentDate,
      seteAMeDez: currentDate,
      seteAMeVinte: currentDate,
      seteAMeTrinta: currentDate,
      seteAMeQuarenta: currentDate,
      seteAMeCinquenta: currentDate,
      setePM: currentDate,
      setePMeDez: currentDate,
      setePMeVinte: currentDate,
      setePMeTrinta: currentDate,
      setePMeQuarenta: currentDate,
      setePMeCinquenta: currentDate,
      oitoAM: currentDate,
      oitoAMeDez: currentDate,
      oitoAMeVinte: currentDate,
      oitoAMeTrinta: currentDate,
      oitoAMeQuarenta: currentDate,
      oitoAMeCinquenta: currentDate,
      oitoPM: currentDate,
      oitoPMeDez: currentDate,
      oitoPMeVinte: currentDate,
      oitoPMeTrinta: currentDate,
      oitoPMeQuarenta: currentDate,
      oitoPMeCinquenta: currentDate,
      noveAM: currentDate,
      noveAMeDez: currentDate,
      noveAMeVinte: currentDate,
      noveAMeTrinta: currentDate,
      noveAMeQuarenta: currentDate,
      noveAMeCinquenta: currentDate,
      novePM: currentDate,
      novePMeDez: currentDate,
      novePMeVinte: currentDate,
      novePMeTrinta: currentDate,
      novePMeQuarenta: currentDate,
      novePMeCinquenta: currentDate,
      dezAM: currentDate,
      dezAMeDez: currentDate,
      dezAMeVinte: currentDate,
      dezAMeTrinta: currentDate,
      dezAMeQuarenta: currentDate,
      dezAMeCinquenta: currentDate,
      dezPM: currentDate,
      dezPMeDez: currentDate,
      dezPMeVinte: currentDate,
      dezPMeTrinta: currentDate,
      dezPMeQuarenta: currentDate,
      dezPMeCinquenta: currentDate,
      onzeAM: currentDate,
      onzeAMeDez: currentDate,
      onzeAMeVinte: currentDate,
      onzeAMeTrinta: currentDate,
      onzeAMeQuarenta: currentDate,
      onzeAMeCinquenta: currentDate,
      onzePM: currentDate,
      onzePMeDez: currentDate,
      onzePMeVinte: currentDate,
      onzePMeTrinta: currentDate,
      onzePMeQuarenta: currentDate,
      onzePMeCinquenta: currentDate,
    };
  });

  describe('Service methods', () => {
    it('should find an element', () => {
      const returnedFromService = Object.assign(
        {
          zeroAM: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPM: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umAM: currentDate.format(DATE_TIME_FORMAT),
          umAMeDez: currentDate.format(DATE_TIME_FORMAT),
          umAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umPM: currentDate.format(DATE_TIME_FORMAT),
          umPMeDez: currentDate.format(DATE_TIME_FORMAT),
          umPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisAM: currentDate.format(DATE_TIME_FORMAT),
          doisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisPM: currentDate.format(DATE_TIME_FORMAT),
          doisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresAM: currentDate.format(DATE_TIME_FORMAT),
          tresAMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresPM: currentDate.format(DATE_TIME_FORMAT),
          tresPMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAM: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPM: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAM: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPM: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisAM: currentDate.format(DATE_TIME_FORMAT),
          seisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisPM: currentDate.format(DATE_TIME_FORMAT),
          seisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seteAM: currentDate.format(DATE_TIME_FORMAT),
          seteAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seteAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seteAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          setePM: currentDate.format(DATE_TIME_FORMAT),
          setePMeDez: currentDate.format(DATE_TIME_FORMAT),
          setePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          setePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          setePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          setePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAM: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPM: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          noveAM: currentDate.format(DATE_TIME_FORMAT),
          noveAMeDez: currentDate.format(DATE_TIME_FORMAT),
          noveAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          noveAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          novePM: currentDate.format(DATE_TIME_FORMAT),
          novePMeDez: currentDate.format(DATE_TIME_FORMAT),
          novePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          novePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          novePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          novePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezAM: currentDate.format(DATE_TIME_FORMAT),
          dezAMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezPM: currentDate.format(DATE_TIME_FORMAT),
          dezPMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAM: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzePM: currentDate.format(DATE_TIME_FORMAT),
          onzePMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
        },
        elemDefault
      );

      service.find(123).subscribe(resp => (expectedResult = resp.body));

      const req = httpMock.expectOne({ method: 'GET' });
      req.flush(returnedFromService);
      expect(expectedResult).toMatchObject(elemDefault);
    });

    it('should create a Blocos', () => {
      const returnedFromService = Object.assign(
        {
          id: 0,
          zeroAM: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPM: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umAM: currentDate.format(DATE_TIME_FORMAT),
          umAMeDez: currentDate.format(DATE_TIME_FORMAT),
          umAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umPM: currentDate.format(DATE_TIME_FORMAT),
          umPMeDez: currentDate.format(DATE_TIME_FORMAT),
          umPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisAM: currentDate.format(DATE_TIME_FORMAT),
          doisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisPM: currentDate.format(DATE_TIME_FORMAT),
          doisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresAM: currentDate.format(DATE_TIME_FORMAT),
          tresAMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresPM: currentDate.format(DATE_TIME_FORMAT),
          tresPMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAM: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPM: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAM: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPM: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisAM: currentDate.format(DATE_TIME_FORMAT),
          seisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisPM: currentDate.format(DATE_TIME_FORMAT),
          seisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seteAM: currentDate.format(DATE_TIME_FORMAT),
          seteAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seteAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seteAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          setePM: currentDate.format(DATE_TIME_FORMAT),
          setePMeDez: currentDate.format(DATE_TIME_FORMAT),
          setePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          setePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          setePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          setePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAM: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPM: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          noveAM: currentDate.format(DATE_TIME_FORMAT),
          noveAMeDez: currentDate.format(DATE_TIME_FORMAT),
          noveAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          noveAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          novePM: currentDate.format(DATE_TIME_FORMAT),
          novePMeDez: currentDate.format(DATE_TIME_FORMAT),
          novePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          novePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          novePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          novePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezAM: currentDate.format(DATE_TIME_FORMAT),
          dezAMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezPM: currentDate.format(DATE_TIME_FORMAT),
          dezPMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAM: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzePM: currentDate.format(DATE_TIME_FORMAT),
          onzePMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
        },
        elemDefault
      );

      const expected = Object.assign(
        {
          zeroAM: currentDate,
          zeroAMeDez: currentDate,
          zeroAMeVinte: currentDate,
          zeroAMeTrinta: currentDate,
          zeroAMeQuarenta: currentDate,
          zeroAMeCinquenta: currentDate,
          zeroPM: currentDate,
          zeroPMeDez: currentDate,
          zeroPMeVinte: currentDate,
          zeroPMeTrinta: currentDate,
          zeroPMeQuarenta: currentDate,
          zeroPMeCinquenta: currentDate,
          umAM: currentDate,
          umAMeDez: currentDate,
          umAMeVinte: currentDate,
          umAMeTrinta: currentDate,
          umAMeQuarenta: currentDate,
          umAMeCinquenta: currentDate,
          umPM: currentDate,
          umPMeDez: currentDate,
          umPMeVinte: currentDate,
          umPMeTrinta: currentDate,
          umPMeQuarenta: currentDate,
          umPMeCinquenta: currentDate,
          doisAM: currentDate,
          doisAMeDez: currentDate,
          doisAMeVinte: currentDate,
          doisAMeTrinta: currentDate,
          doisAMeQuarenta: currentDate,
          doisAMeCinquenta: currentDate,
          doisPM: currentDate,
          doisPMeDez: currentDate,
          doisPMeVinte: currentDate,
          doisPMeTrinta: currentDate,
          doisPMeQuarenta: currentDate,
          doisPMeCinquenta: currentDate,
          tresAM: currentDate,
          tresAMeDez: currentDate,
          tresAMeVinte: currentDate,
          tresAMeTrinta: currentDate,
          tresAMeQuarenta: currentDate,
          tresAMeCinquenta: currentDate,
          tresPM: currentDate,
          tresPMeDez: currentDate,
          tresPMeVinte: currentDate,
          tresPMeTrinta: currentDate,
          tresPMeQuarenta: currentDate,
          tresPMeCinquenta: currentDate,
          quatroAM: currentDate,
          quatroAMeDez: currentDate,
          quatroAMeVinte: currentDate,
          quatroAMeTrinta: currentDate,
          quatroAMeQuarenta: currentDate,
          quatroAMeCinquenta: currentDate,
          quatroPM: currentDate,
          quatroPMeDez: currentDate,
          quatroPMeVinte: currentDate,
          quatroPMeTrinta: currentDate,
          quatroPMeQuarenta: currentDate,
          quatroPMeCinquenta: currentDate,
          cincoAM: currentDate,
          cincoAMeDez: currentDate,
          cincoAMeVinte: currentDate,
          cincoAMeTrinta: currentDate,
          cincoAMeQuarenta: currentDate,
          cincoAMeCinquenta: currentDate,
          cincoPM: currentDate,
          cincoPMeDez: currentDate,
          cincoPMeVinte: currentDate,
          cincoPMeTrinta: currentDate,
          cincoPMeQuarenta: currentDate,
          cincoPMeCinquenta: currentDate,
          seisAM: currentDate,
          seisAMeDez: currentDate,
          seisAMeVinte: currentDate,
          seisAMeTrinta: currentDate,
          seisAMeQuarenta: currentDate,
          seisAMeCinquenta: currentDate,
          seisPM: currentDate,
          seisPMeDez: currentDate,
          seisPMeVinte: currentDate,
          seisPMeTrinta: currentDate,
          seisPMeQuarenta: currentDate,
          seisPMeCinquenta: currentDate,
          seteAM: currentDate,
          seteAMeDez: currentDate,
          seteAMeVinte: currentDate,
          seteAMeTrinta: currentDate,
          seteAMeQuarenta: currentDate,
          seteAMeCinquenta: currentDate,
          setePM: currentDate,
          setePMeDez: currentDate,
          setePMeVinte: currentDate,
          setePMeTrinta: currentDate,
          setePMeQuarenta: currentDate,
          setePMeCinquenta: currentDate,
          oitoAM: currentDate,
          oitoAMeDez: currentDate,
          oitoAMeVinte: currentDate,
          oitoAMeTrinta: currentDate,
          oitoAMeQuarenta: currentDate,
          oitoAMeCinquenta: currentDate,
          oitoPM: currentDate,
          oitoPMeDez: currentDate,
          oitoPMeVinte: currentDate,
          oitoPMeTrinta: currentDate,
          oitoPMeQuarenta: currentDate,
          oitoPMeCinquenta: currentDate,
          noveAM: currentDate,
          noveAMeDez: currentDate,
          noveAMeVinte: currentDate,
          noveAMeTrinta: currentDate,
          noveAMeQuarenta: currentDate,
          noveAMeCinquenta: currentDate,
          novePM: currentDate,
          novePMeDez: currentDate,
          novePMeVinte: currentDate,
          novePMeTrinta: currentDate,
          novePMeQuarenta: currentDate,
          novePMeCinquenta: currentDate,
          dezAM: currentDate,
          dezAMeDez: currentDate,
          dezAMeVinte: currentDate,
          dezAMeTrinta: currentDate,
          dezAMeQuarenta: currentDate,
          dezAMeCinquenta: currentDate,
          dezPM: currentDate,
          dezPMeDez: currentDate,
          dezPMeVinte: currentDate,
          dezPMeTrinta: currentDate,
          dezPMeQuarenta: currentDate,
          dezPMeCinquenta: currentDate,
          onzeAM: currentDate,
          onzeAMeDez: currentDate,
          onzeAMeVinte: currentDate,
          onzeAMeTrinta: currentDate,
          onzeAMeQuarenta: currentDate,
          onzeAMeCinquenta: currentDate,
          onzePM: currentDate,
          onzePMeDez: currentDate,
          onzePMeVinte: currentDate,
          onzePMeTrinta: currentDate,
          onzePMeQuarenta: currentDate,
          onzePMeCinquenta: currentDate,
        },
        returnedFromService
      );

      service.create(new Blocos()).subscribe(resp => (expectedResult = resp.body));

      const req = httpMock.expectOne({ method: 'POST' });
      req.flush(returnedFromService);
      expect(expectedResult).toMatchObject(expected);
    });

    it('should update a Blocos', () => {
      const returnedFromService = Object.assign(
        {
          id: 1,
          zeroAM: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPM: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umAM: currentDate.format(DATE_TIME_FORMAT),
          umAMeDez: currentDate.format(DATE_TIME_FORMAT),
          umAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umPM: currentDate.format(DATE_TIME_FORMAT),
          umPMeDez: currentDate.format(DATE_TIME_FORMAT),
          umPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisAM: currentDate.format(DATE_TIME_FORMAT),
          doisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisPM: currentDate.format(DATE_TIME_FORMAT),
          doisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresAM: currentDate.format(DATE_TIME_FORMAT),
          tresAMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresPM: currentDate.format(DATE_TIME_FORMAT),
          tresPMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAM: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPM: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAM: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPM: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisAM: currentDate.format(DATE_TIME_FORMAT),
          seisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisPM: currentDate.format(DATE_TIME_FORMAT),
          seisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seteAM: currentDate.format(DATE_TIME_FORMAT),
          seteAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seteAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seteAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          setePM: currentDate.format(DATE_TIME_FORMAT),
          setePMeDez: currentDate.format(DATE_TIME_FORMAT),
          setePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          setePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          setePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          setePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAM: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPM: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          noveAM: currentDate.format(DATE_TIME_FORMAT),
          noveAMeDez: currentDate.format(DATE_TIME_FORMAT),
          noveAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          noveAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          novePM: currentDate.format(DATE_TIME_FORMAT),
          novePMeDez: currentDate.format(DATE_TIME_FORMAT),
          novePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          novePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          novePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          novePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezAM: currentDate.format(DATE_TIME_FORMAT),
          dezAMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezPM: currentDate.format(DATE_TIME_FORMAT),
          dezPMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAM: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzePM: currentDate.format(DATE_TIME_FORMAT),
          onzePMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
        },
        elemDefault
      );

      const expected = Object.assign(
        {
          zeroAM: currentDate,
          zeroAMeDez: currentDate,
          zeroAMeVinte: currentDate,
          zeroAMeTrinta: currentDate,
          zeroAMeQuarenta: currentDate,
          zeroAMeCinquenta: currentDate,
          zeroPM: currentDate,
          zeroPMeDez: currentDate,
          zeroPMeVinte: currentDate,
          zeroPMeTrinta: currentDate,
          zeroPMeQuarenta: currentDate,
          zeroPMeCinquenta: currentDate,
          umAM: currentDate,
          umAMeDez: currentDate,
          umAMeVinte: currentDate,
          umAMeTrinta: currentDate,
          umAMeQuarenta: currentDate,
          umAMeCinquenta: currentDate,
          umPM: currentDate,
          umPMeDez: currentDate,
          umPMeVinte: currentDate,
          umPMeTrinta: currentDate,
          umPMeQuarenta: currentDate,
          umPMeCinquenta: currentDate,
          doisAM: currentDate,
          doisAMeDez: currentDate,
          doisAMeVinte: currentDate,
          doisAMeTrinta: currentDate,
          doisAMeQuarenta: currentDate,
          doisAMeCinquenta: currentDate,
          doisPM: currentDate,
          doisPMeDez: currentDate,
          doisPMeVinte: currentDate,
          doisPMeTrinta: currentDate,
          doisPMeQuarenta: currentDate,
          doisPMeCinquenta: currentDate,
          tresAM: currentDate,
          tresAMeDez: currentDate,
          tresAMeVinte: currentDate,
          tresAMeTrinta: currentDate,
          tresAMeQuarenta: currentDate,
          tresAMeCinquenta: currentDate,
          tresPM: currentDate,
          tresPMeDez: currentDate,
          tresPMeVinte: currentDate,
          tresPMeTrinta: currentDate,
          tresPMeQuarenta: currentDate,
          tresPMeCinquenta: currentDate,
          quatroAM: currentDate,
          quatroAMeDez: currentDate,
          quatroAMeVinte: currentDate,
          quatroAMeTrinta: currentDate,
          quatroAMeQuarenta: currentDate,
          quatroAMeCinquenta: currentDate,
          quatroPM: currentDate,
          quatroPMeDez: currentDate,
          quatroPMeVinte: currentDate,
          quatroPMeTrinta: currentDate,
          quatroPMeQuarenta: currentDate,
          quatroPMeCinquenta: currentDate,
          cincoAM: currentDate,
          cincoAMeDez: currentDate,
          cincoAMeVinte: currentDate,
          cincoAMeTrinta: currentDate,
          cincoAMeQuarenta: currentDate,
          cincoAMeCinquenta: currentDate,
          cincoPM: currentDate,
          cincoPMeDez: currentDate,
          cincoPMeVinte: currentDate,
          cincoPMeTrinta: currentDate,
          cincoPMeQuarenta: currentDate,
          cincoPMeCinquenta: currentDate,
          seisAM: currentDate,
          seisAMeDez: currentDate,
          seisAMeVinte: currentDate,
          seisAMeTrinta: currentDate,
          seisAMeQuarenta: currentDate,
          seisAMeCinquenta: currentDate,
          seisPM: currentDate,
          seisPMeDez: currentDate,
          seisPMeVinte: currentDate,
          seisPMeTrinta: currentDate,
          seisPMeQuarenta: currentDate,
          seisPMeCinquenta: currentDate,
          seteAM: currentDate,
          seteAMeDez: currentDate,
          seteAMeVinte: currentDate,
          seteAMeTrinta: currentDate,
          seteAMeQuarenta: currentDate,
          seteAMeCinquenta: currentDate,
          setePM: currentDate,
          setePMeDez: currentDate,
          setePMeVinte: currentDate,
          setePMeTrinta: currentDate,
          setePMeQuarenta: currentDate,
          setePMeCinquenta: currentDate,
          oitoAM: currentDate,
          oitoAMeDez: currentDate,
          oitoAMeVinte: currentDate,
          oitoAMeTrinta: currentDate,
          oitoAMeQuarenta: currentDate,
          oitoAMeCinquenta: currentDate,
          oitoPM: currentDate,
          oitoPMeDez: currentDate,
          oitoPMeVinte: currentDate,
          oitoPMeTrinta: currentDate,
          oitoPMeQuarenta: currentDate,
          oitoPMeCinquenta: currentDate,
          noveAM: currentDate,
          noveAMeDez: currentDate,
          noveAMeVinte: currentDate,
          noveAMeTrinta: currentDate,
          noveAMeQuarenta: currentDate,
          noveAMeCinquenta: currentDate,
          novePM: currentDate,
          novePMeDez: currentDate,
          novePMeVinte: currentDate,
          novePMeTrinta: currentDate,
          novePMeQuarenta: currentDate,
          novePMeCinquenta: currentDate,
          dezAM: currentDate,
          dezAMeDez: currentDate,
          dezAMeVinte: currentDate,
          dezAMeTrinta: currentDate,
          dezAMeQuarenta: currentDate,
          dezAMeCinquenta: currentDate,
          dezPM: currentDate,
          dezPMeDez: currentDate,
          dezPMeVinte: currentDate,
          dezPMeTrinta: currentDate,
          dezPMeQuarenta: currentDate,
          dezPMeCinquenta: currentDate,
          onzeAM: currentDate,
          onzeAMeDez: currentDate,
          onzeAMeVinte: currentDate,
          onzeAMeTrinta: currentDate,
          onzeAMeQuarenta: currentDate,
          onzeAMeCinquenta: currentDate,
          onzePM: currentDate,
          onzePMeDez: currentDate,
          onzePMeVinte: currentDate,
          onzePMeTrinta: currentDate,
          onzePMeQuarenta: currentDate,
          onzePMeCinquenta: currentDate,
        },
        returnedFromService
      );

      service.update(expected).subscribe(resp => (expectedResult = resp.body));

      const req = httpMock.expectOne({ method: 'PUT' });
      req.flush(returnedFromService);
      expect(expectedResult).toMatchObject(expected);
    });

    it('should partial update a Blocos', () => {
      const patchObject = Object.assign(
        {
          zeroAM: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umAM: currentDate.format(DATE_TIME_FORMAT),
          umAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umPM: currentDate.format(DATE_TIME_FORMAT),
          umPMeDez: currentDate.format(DATE_TIME_FORMAT),
          umPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisPM: currentDate.format(DATE_TIME_FORMAT),
          doisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresAM: currentDate.format(DATE_TIME_FORMAT),
          tresAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresPM: currentDate.format(DATE_TIME_FORMAT),
          tresPMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroAM: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPM: currentDate.format(DATE_TIME_FORMAT),
          seisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisPM: currentDate.format(DATE_TIME_FORMAT),
          seisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          setePM: currentDate.format(DATE_TIME_FORMAT),
          setePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAM: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeDez: currentDate.format(DATE_TIME_FORMAT),
          noveAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          noveAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          novePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezAM: currentDate.format(DATE_TIME_FORMAT),
          dezAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAM: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
        },
        new Blocos()
      );

      const returnedFromService = Object.assign(patchObject, elemDefault);

      const expected = Object.assign(
        {
          zeroAM: currentDate,
          zeroAMeDez: currentDate,
          zeroAMeVinte: currentDate,
          zeroAMeTrinta: currentDate,
          zeroAMeQuarenta: currentDate,
          zeroAMeCinquenta: currentDate,
          zeroPM: currentDate,
          zeroPMeDez: currentDate,
          zeroPMeVinte: currentDate,
          zeroPMeTrinta: currentDate,
          zeroPMeQuarenta: currentDate,
          zeroPMeCinquenta: currentDate,
          umAM: currentDate,
          umAMeDez: currentDate,
          umAMeVinte: currentDate,
          umAMeTrinta: currentDate,
          umAMeQuarenta: currentDate,
          umAMeCinquenta: currentDate,
          umPM: currentDate,
          umPMeDez: currentDate,
          umPMeVinte: currentDate,
          umPMeTrinta: currentDate,
          umPMeQuarenta: currentDate,
          umPMeCinquenta: currentDate,
          doisAM: currentDate,
          doisAMeDez: currentDate,
          doisAMeVinte: currentDate,
          doisAMeTrinta: currentDate,
          doisAMeQuarenta: currentDate,
          doisAMeCinquenta: currentDate,
          doisPM: currentDate,
          doisPMeDez: currentDate,
          doisPMeVinte: currentDate,
          doisPMeTrinta: currentDate,
          doisPMeQuarenta: currentDate,
          doisPMeCinquenta: currentDate,
          tresAM: currentDate,
          tresAMeDez: currentDate,
          tresAMeVinte: currentDate,
          tresAMeTrinta: currentDate,
          tresAMeQuarenta: currentDate,
          tresAMeCinquenta: currentDate,
          tresPM: currentDate,
          tresPMeDez: currentDate,
          tresPMeVinte: currentDate,
          tresPMeTrinta: currentDate,
          tresPMeQuarenta: currentDate,
          tresPMeCinquenta: currentDate,
          quatroAM: currentDate,
          quatroAMeDez: currentDate,
          quatroAMeVinte: currentDate,
          quatroAMeTrinta: currentDate,
          quatroAMeQuarenta: currentDate,
          quatroAMeCinquenta: currentDate,
          quatroPM: currentDate,
          quatroPMeDez: currentDate,
          quatroPMeVinte: currentDate,
          quatroPMeTrinta: currentDate,
          quatroPMeQuarenta: currentDate,
          quatroPMeCinquenta: currentDate,
          cincoAM: currentDate,
          cincoAMeDez: currentDate,
          cincoAMeVinte: currentDate,
          cincoAMeTrinta: currentDate,
          cincoAMeQuarenta: currentDate,
          cincoAMeCinquenta: currentDate,
          cincoPM: currentDate,
          cincoPMeDez: currentDate,
          cincoPMeVinte: currentDate,
          cincoPMeTrinta: currentDate,
          cincoPMeQuarenta: currentDate,
          cincoPMeCinquenta: currentDate,
          seisAM: currentDate,
          seisAMeDez: currentDate,
          seisAMeVinte: currentDate,
          seisAMeTrinta: currentDate,
          seisAMeQuarenta: currentDate,
          seisAMeCinquenta: currentDate,
          seisPM: currentDate,
          seisPMeDez: currentDate,
          seisPMeVinte: currentDate,
          seisPMeTrinta: currentDate,
          seisPMeQuarenta: currentDate,
          seisPMeCinquenta: currentDate,
          seteAM: currentDate,
          seteAMeDez: currentDate,
          seteAMeVinte: currentDate,
          seteAMeTrinta: currentDate,
          seteAMeQuarenta: currentDate,
          seteAMeCinquenta: currentDate,
          setePM: currentDate,
          setePMeDez: currentDate,
          setePMeVinte: currentDate,
          setePMeTrinta: currentDate,
          setePMeQuarenta: currentDate,
          setePMeCinquenta: currentDate,
          oitoAM: currentDate,
          oitoAMeDez: currentDate,
          oitoAMeVinte: currentDate,
          oitoAMeTrinta: currentDate,
          oitoAMeQuarenta: currentDate,
          oitoAMeCinquenta: currentDate,
          oitoPM: currentDate,
          oitoPMeDez: currentDate,
          oitoPMeVinte: currentDate,
          oitoPMeTrinta: currentDate,
          oitoPMeQuarenta: currentDate,
          oitoPMeCinquenta: currentDate,
          noveAM: currentDate,
          noveAMeDez: currentDate,
          noveAMeVinte: currentDate,
          noveAMeTrinta: currentDate,
          noveAMeQuarenta: currentDate,
          noveAMeCinquenta: currentDate,
          novePM: currentDate,
          novePMeDez: currentDate,
          novePMeVinte: currentDate,
          novePMeTrinta: currentDate,
          novePMeQuarenta: currentDate,
          novePMeCinquenta: currentDate,
          dezAM: currentDate,
          dezAMeDez: currentDate,
          dezAMeVinte: currentDate,
          dezAMeTrinta: currentDate,
          dezAMeQuarenta: currentDate,
          dezAMeCinquenta: currentDate,
          dezPM: currentDate,
          dezPMeDez: currentDate,
          dezPMeVinte: currentDate,
          dezPMeTrinta: currentDate,
          dezPMeQuarenta: currentDate,
          dezPMeCinquenta: currentDate,
          onzeAM: currentDate,
          onzeAMeDez: currentDate,
          onzeAMeVinte: currentDate,
          onzeAMeTrinta: currentDate,
          onzeAMeQuarenta: currentDate,
          onzeAMeCinquenta: currentDate,
          onzePM: currentDate,
          onzePMeDez: currentDate,
          onzePMeVinte: currentDate,
          onzePMeTrinta: currentDate,
          onzePMeQuarenta: currentDate,
          onzePMeCinquenta: currentDate,
        },
        returnedFromService
      );

      service.partialUpdate(patchObject).subscribe(resp => (expectedResult = resp.body));

      const req = httpMock.expectOne({ method: 'PATCH' });
      req.flush(returnedFromService);
      expect(expectedResult).toMatchObject(expected);
    });

    it('should return a list of Blocos', () => {
      const returnedFromService = Object.assign(
        {
          id: 1,
          zeroAM: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPM: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          zeroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umAM: currentDate.format(DATE_TIME_FORMAT),
          umAMeDez: currentDate.format(DATE_TIME_FORMAT),
          umAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          umPM: currentDate.format(DATE_TIME_FORMAT),
          umPMeDez: currentDate.format(DATE_TIME_FORMAT),
          umPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          umPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          umPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          umPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisAM: currentDate.format(DATE_TIME_FORMAT),
          doisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          doisPM: currentDate.format(DATE_TIME_FORMAT),
          doisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          doisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          doisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          doisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresAM: currentDate.format(DATE_TIME_FORMAT),
          tresAMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          tresPM: currentDate.format(DATE_TIME_FORMAT),
          tresPMeDez: currentDate.format(DATE_TIME_FORMAT),
          tresPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          tresPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          tresPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAM: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPM: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeDez: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          quatroPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAM: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPM: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          cincoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisAM: currentDate.format(DATE_TIME_FORMAT),
          seisAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seisPM: currentDate.format(DATE_TIME_FORMAT),
          seisPMeDez: currentDate.format(DATE_TIME_FORMAT),
          seisPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seisPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seisPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          seteAM: currentDate.format(DATE_TIME_FORMAT),
          seteAMeDez: currentDate.format(DATE_TIME_FORMAT),
          seteAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          seteAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          seteAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          setePM: currentDate.format(DATE_TIME_FORMAT),
          setePMeDez: currentDate.format(DATE_TIME_FORMAT),
          setePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          setePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          setePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          setePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAM: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPM: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeDez: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          oitoPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          noveAM: currentDate.format(DATE_TIME_FORMAT),
          noveAMeDez: currentDate.format(DATE_TIME_FORMAT),
          noveAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          noveAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          noveAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          novePM: currentDate.format(DATE_TIME_FORMAT),
          novePMeDez: currentDate.format(DATE_TIME_FORMAT),
          novePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          novePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          novePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          novePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezAM: currentDate.format(DATE_TIME_FORMAT),
          dezAMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          dezPM: currentDate.format(DATE_TIME_FORMAT),
          dezPMeDez: currentDate.format(DATE_TIME_FORMAT),
          dezPMeVinte: currentDate.format(DATE_TIME_FORMAT),
          dezPMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          dezPMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAM: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzeAMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
          onzePM: currentDate.format(DATE_TIME_FORMAT),
          onzePMeDez: currentDate.format(DATE_TIME_FORMAT),
          onzePMeVinte: currentDate.format(DATE_TIME_FORMAT),
          onzePMeTrinta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeQuarenta: currentDate.format(DATE_TIME_FORMAT),
          onzePMeCinquenta: currentDate.format(DATE_TIME_FORMAT),
        },
        elemDefault
      );

      const expected = Object.assign(
        {
          zeroAM: currentDate,
          zeroAMeDez: currentDate,
          zeroAMeVinte: currentDate,
          zeroAMeTrinta: currentDate,
          zeroAMeQuarenta: currentDate,
          zeroAMeCinquenta: currentDate,
          zeroPM: currentDate,
          zeroPMeDez: currentDate,
          zeroPMeVinte: currentDate,
          zeroPMeTrinta: currentDate,
          zeroPMeQuarenta: currentDate,
          zeroPMeCinquenta: currentDate,
          umAM: currentDate,
          umAMeDez: currentDate,
          umAMeVinte: currentDate,
          umAMeTrinta: currentDate,
          umAMeQuarenta: currentDate,
          umAMeCinquenta: currentDate,
          umPM: currentDate,
          umPMeDez: currentDate,
          umPMeVinte: currentDate,
          umPMeTrinta: currentDate,
          umPMeQuarenta: currentDate,
          umPMeCinquenta: currentDate,
          doisAM: currentDate,
          doisAMeDez: currentDate,
          doisAMeVinte: currentDate,
          doisAMeTrinta: currentDate,
          doisAMeQuarenta: currentDate,
          doisAMeCinquenta: currentDate,
          doisPM: currentDate,
          doisPMeDez: currentDate,
          doisPMeVinte: currentDate,
          doisPMeTrinta: currentDate,
          doisPMeQuarenta: currentDate,
          doisPMeCinquenta: currentDate,
          tresAM: currentDate,
          tresAMeDez: currentDate,
          tresAMeVinte: currentDate,
          tresAMeTrinta: currentDate,
          tresAMeQuarenta: currentDate,
          tresAMeCinquenta: currentDate,
          tresPM: currentDate,
          tresPMeDez: currentDate,
          tresPMeVinte: currentDate,
          tresPMeTrinta: currentDate,
          tresPMeQuarenta: currentDate,
          tresPMeCinquenta: currentDate,
          quatroAM: currentDate,
          quatroAMeDez: currentDate,
          quatroAMeVinte: currentDate,
          quatroAMeTrinta: currentDate,
          quatroAMeQuarenta: currentDate,
          quatroAMeCinquenta: currentDate,
          quatroPM: currentDate,
          quatroPMeDez: currentDate,
          quatroPMeVinte: currentDate,
          quatroPMeTrinta: currentDate,
          quatroPMeQuarenta: currentDate,
          quatroPMeCinquenta: currentDate,
          cincoAM: currentDate,
          cincoAMeDez: currentDate,
          cincoAMeVinte: currentDate,
          cincoAMeTrinta: currentDate,
          cincoAMeQuarenta: currentDate,
          cincoAMeCinquenta: currentDate,
          cincoPM: currentDate,
          cincoPMeDez: currentDate,
          cincoPMeVinte: currentDate,
          cincoPMeTrinta: currentDate,
          cincoPMeQuarenta: currentDate,
          cincoPMeCinquenta: currentDate,
          seisAM: currentDate,
          seisAMeDez: currentDate,
          seisAMeVinte: currentDate,
          seisAMeTrinta: currentDate,
          seisAMeQuarenta: currentDate,
          seisAMeCinquenta: currentDate,
          seisPM: currentDate,
          seisPMeDez: currentDate,
          seisPMeVinte: currentDate,
          seisPMeTrinta: currentDate,
          seisPMeQuarenta: currentDate,
          seisPMeCinquenta: currentDate,
          seteAM: currentDate,
          seteAMeDez: currentDate,
          seteAMeVinte: currentDate,
          seteAMeTrinta: currentDate,
          seteAMeQuarenta: currentDate,
          seteAMeCinquenta: currentDate,
          setePM: currentDate,
          setePMeDez: currentDate,
          setePMeVinte: currentDate,
          setePMeTrinta: currentDate,
          setePMeQuarenta: currentDate,
          setePMeCinquenta: currentDate,
          oitoAM: currentDate,
          oitoAMeDez: currentDate,
          oitoAMeVinte: currentDate,
          oitoAMeTrinta: currentDate,
          oitoAMeQuarenta: currentDate,
          oitoAMeCinquenta: currentDate,
          oitoPM: currentDate,
          oitoPMeDez: currentDate,
          oitoPMeVinte: currentDate,
          oitoPMeTrinta: currentDate,
          oitoPMeQuarenta: currentDate,
          oitoPMeCinquenta: currentDate,
          noveAM: currentDate,
          noveAMeDez: currentDate,
          noveAMeVinte: currentDate,
          noveAMeTrinta: currentDate,
          noveAMeQuarenta: currentDate,
          noveAMeCinquenta: currentDate,
          novePM: currentDate,
          novePMeDez: currentDate,
          novePMeVinte: currentDate,
          novePMeTrinta: currentDate,
          novePMeQuarenta: currentDate,
          novePMeCinquenta: currentDate,
          dezAM: currentDate,
          dezAMeDez: currentDate,
          dezAMeVinte: currentDate,
          dezAMeTrinta: currentDate,
          dezAMeQuarenta: currentDate,
          dezAMeCinquenta: currentDate,
          dezPM: currentDate,
          dezPMeDez: currentDate,
          dezPMeVinte: currentDate,
          dezPMeTrinta: currentDate,
          dezPMeQuarenta: currentDate,
          dezPMeCinquenta: currentDate,
          onzeAM: currentDate,
          onzeAMeDez: currentDate,
          onzeAMeVinte: currentDate,
          onzeAMeTrinta: currentDate,
          onzeAMeQuarenta: currentDate,
          onzeAMeCinquenta: currentDate,
          onzePM: currentDate,
          onzePMeDez: currentDate,
          onzePMeVinte: currentDate,
          onzePMeTrinta: currentDate,
          onzePMeQuarenta: currentDate,
          onzePMeCinquenta: currentDate,
        },
        returnedFromService
      );

      service.query().subscribe(resp => (expectedResult = resp.body));

      const req = httpMock.expectOne({ method: 'GET' });
      req.flush([returnedFromService]);
      httpMock.verify();
      expect(expectedResult).toContainEqual(expected);
    });

    it('should delete a Blocos', () => {
      service.delete(123).subscribe(resp => (expectedResult = resp.ok));

      const req = httpMock.expectOne({ method: 'DELETE' });
      req.flush({ status: 200 });
      expect(expectedResult);
    });

    describe('addBlocosToCollectionIfMissing', () => {
      it('should add a Blocos to an empty array', () => {
        const blocos: IBlocos = { id: 123 };
        expectedResult = service.addBlocosToCollectionIfMissing([], blocos);
        expect(expectedResult).toHaveLength(1);
        expect(expectedResult).toContain(blocos);
      });

      it('should not add a Blocos to an array that contains it', () => {
        const blocos: IBlocos = { id: 123 };
        const blocosCollection: IBlocos[] = [
          {
            ...blocos,
          },
          { id: 456 },
        ];
        expectedResult = service.addBlocosToCollectionIfMissing(blocosCollection, blocos);
        expect(expectedResult).toHaveLength(2);
      });

      it("should add a Blocos to an array that doesn't contain it", () => {
        const blocos: IBlocos = { id: 123 };
        const blocosCollection: IBlocos[] = [{ id: 456 }];
        expectedResult = service.addBlocosToCollectionIfMissing(blocosCollection, blocos);
        expect(expectedResult).toHaveLength(2);
        expect(expectedResult).toContain(blocos);
      });

      it('should add only unique Blocos to an array', () => {
        const blocosArray: IBlocos[] = [{ id: 123 }, { id: 456 }, { id: 55948 }];
        const blocosCollection: IBlocos[] = [{ id: 123 }];
        expectedResult = service.addBlocosToCollectionIfMissing(blocosCollection, ...blocosArray);
        expect(expectedResult).toHaveLength(3);
      });

      it('should accept varargs', () => {
        const blocos: IBlocos = { id: 123 };
        const blocos2: IBlocos = { id: 456 };
        expectedResult = service.addBlocosToCollectionIfMissing([], blocos, blocos2);
        expect(expectedResult).toHaveLength(2);
        expect(expectedResult).toContain(blocos);
        expect(expectedResult).toContain(blocos2);
      });

      it('should accept null and undefined values', () => {
        const blocos: IBlocos = { id: 123 };
        expectedResult = service.addBlocosToCollectionIfMissing([], null, blocos, undefined);
        expect(expectedResult).toHaveLength(1);
        expect(expectedResult).toContain(blocos);
      });

      it('should return initial array if no Blocos is added', () => {
        const blocosCollection: IBlocos[] = [{ id: 123 }];
        expectedResult = service.addBlocosToCollectionIfMissing(blocosCollection, undefined, null);
        expect(expectedResult).toEqual(blocosCollection);
      });
    });
  });

  afterEach(() => {
    httpMock.verify();
  });
});
